### ISSUE TITLE
Not working on Django 1.10

### ISSUE THREAD

**Issue by rafaelhdr** [fcurella/django-recommends#35]
Testing on Django 1.9, it works fine. But on Django 1.10, raise `AttributeError: type object 'BaseCommand' has no attribute 'option_list'`.

Checking on [StackOverflow](http://stackoverflow.com/questions/35181133/python-attribute-error-when-running-script-type-object-basecommand-has-no-att), *"BaseCommand.option_list is deprecated in Django 1.8 and removed in Django 1.10."*.

*options_list* is at https://github.com/fcurella/django-recommends/blob/develop/recommends/management/commands/recommends_precompute.py .

Thanks
